// Code generated by thriftgo (0.3.12). DO NOT EDIT.

package sc_bff_api

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ColumnQuoteStatus int64

const (
	ColumnQuoteStatus_NEW ColumnQuoteStatus = 0
	ColumnQuoteStatus_OK  ColumnQuoteStatus = 1
)

func (p ColumnQuoteStatus) String() string {
	switch p {
	case ColumnQuoteStatus_NEW:
		return "NEW"
	case ColumnQuoteStatus_OK:
		return "OK"
	}
	return "<UNSET>"
}

func ColumnQuoteStatusFromString(s string) (ColumnQuoteStatus, error) {
	switch s {
	case "NEW":
		return ColumnQuoteStatus_NEW, nil
	case "OK":
		return ColumnQuoteStatus_OK, nil
	}
	return ColumnQuoteStatus(0), fmt.Errorf("not a valid ColumnQuoteStatus string")
}

func ColumnQuoteStatusPtr(v ColumnQuoteStatus) *ColumnQuoteStatus { return &v }
func (p *ColumnQuoteStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ColumnQuoteStatus(result.Int64)
	return
}

func (p *ColumnQuoteStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
