// Code generated by Kitex v0.9.1. DO NOT EDIT.

package subscriptionservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	sc_subscription_api "github.com/eyebluecn/sc-subscription-idl/kitex_gen/sc_subscription_api"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SubscriptionPage": kitex.NewMethodInfo(
		subscriptionPageHandler,
		newSubscriptionServiceSubscriptionPageArgs,
		newSubscriptionServiceSubscriptionPageResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SubscriptionPrepare": kitex.NewMethodInfo(
		subscriptionPrepareHandler,
		newSubscriptionServiceSubscriptionPrepareArgs,
		newSubscriptionServiceSubscriptionPrepareResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	subscriptionServiceServiceInfo                = NewServiceInfo()
	subscriptionServiceServiceInfoForClient       = NewServiceInfoForClient()
	subscriptionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return subscriptionServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return subscriptionServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return subscriptionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "SubscriptionService"
	handlerType := (*sc_subscription_api.SubscriptionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sc_subscription_api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func subscriptionPageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_subscription_api.SubscriptionServiceSubscriptionPageArgs)
	realResult := result.(*sc_subscription_api.SubscriptionServiceSubscriptionPageResult)
	success, err := handler.(sc_subscription_api.SubscriptionService).SubscriptionPage(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSubscriptionServiceSubscriptionPageArgs() interface{} {
	return sc_subscription_api.NewSubscriptionServiceSubscriptionPageArgs()
}

func newSubscriptionServiceSubscriptionPageResult() interface{} {
	return sc_subscription_api.NewSubscriptionServiceSubscriptionPageResult()
}

func subscriptionPrepareHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*sc_subscription_api.SubscriptionServiceSubscriptionPrepareArgs)
	realResult := result.(*sc_subscription_api.SubscriptionServiceSubscriptionPrepareResult)
	success, err := handler.(sc_subscription_api.SubscriptionService).SubscriptionPrepare(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newSubscriptionServiceSubscriptionPrepareArgs() interface{} {
	return sc_subscription_api.NewSubscriptionServiceSubscriptionPrepareArgs()
}

func newSubscriptionServiceSubscriptionPrepareResult() interface{} {
	return sc_subscription_api.NewSubscriptionServiceSubscriptionPrepareResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SubscriptionPage(ctx context.Context, request *sc_subscription_api.SubscriptionPageRequest) (r *sc_subscription_api.SubscriptionPageResponse, err error) {
	var _args sc_subscription_api.SubscriptionServiceSubscriptionPageArgs
	_args.Request = request
	var _result sc_subscription_api.SubscriptionServiceSubscriptionPageResult
	if err = p.c.Call(ctx, "SubscriptionPage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SubscriptionPrepare(ctx context.Context, request *sc_subscription_api.SubscriptionPrepareRequest) (r *sc_subscription_api.SubscriptionPrepareResponse, err error) {
	var _args sc_subscription_api.SubscriptionServiceSubscriptionPrepareArgs
	_args.Request = request
	var _result sc_subscription_api.SubscriptionServiceSubscriptionPrepareResult
	if err = p.c.Call(ctx, "SubscriptionPrepare", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
